version: '3.8'
services:
  upscaler:
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1','3','4','5']
            capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/data:rw
    build: upscaler
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Europe/Moscow
